### PR TITLE
232: Fix crash due to currency API update

### LINKED ISSUE #232: Currency Converter API Down (Again)
From the [ECB website](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html):

> Please note that [Croatia adopted the euro](https://www.ecb.europa.eu/euro/changeover/croatia/html/index.en.html) on 1 January 2023. The Croatian kuna has therefore been removed from the ECB’s list of euro foreign exchange reference rates and has not been replaced in the list by another currency.

As such, the app behaviour described in #222 has started happening again

### PR DESCRIPTION
**Pull request by physphil**
Fixes #232 

This PR contains two commits:
1. Remove the Croation Kuna currency as it is no longer used
2. Refactor to ensure app won't crash if API experiences further changes

### CODE REVIEW

File: app/src/main/java/com/physphil/android/unitconverterultimate/util/Conversions.java [hunk 1]
```diff
@@ -135,43 +137,63 @@ public void updateCurrencyConversions(Context context) {
...
+            return new Unit(
+                /* id */ id,
+                /* labelResource */ labelResource,
+                /* conversionToBase */ 1 / currencyMap.get(country),
+                /* conversionFromBase */ currencyMap.get(country)
+            );
+        } catch (NullPointerException ex) {
+            // Currency not present
+            return null;
+        }
```
Comment (tacsipacsi) [inline app/src/main/java/com/physphil/android/unitconverterultimate/util/Conversions.java:188]: `NullPointerException` can be thrown at several places, catching and ignoring it can hide programming errors. Instead, I’d add an explicit null check:
```java
Double rate = currencyMap.get(country);
return rate != null ? new Unit(id, labelResource, 1 / rate, rate) : null;
```
